### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by holyPigeon** [holyPigeon/clean-up#3]
## 📄 Describe
application.properties 설정을 통해 데이터베이스 및 MySQL 연동을 완료합니다.
베이스 엔티티 구현을 통해 각 엔티티들이 시간 및 생성자, 수정자 정보를 포함할 수 있도록 세팅합니다.

## ✅ Tasks
- [x] 데이터베이스 및 MySQL 연동
- [x] 베이스 엔티티 2종류 구현 (`BaseEntity`, `BaseTimeEntity`) 
- [x] 커스텀 API response 핸들러 구현 

## 🙋🏻 More
이후 JPA 또는 로깅 관련 설정이 추가될 예정입니다.
