### ISSUE TITLE
파일 입출력을 통한 주차장 데이터 추출 및 반환 기능 구현

### ISSUE THREAD

**Issue by holyPigeon** [holyPigeon/clean-up#8]
## 📄 Describe
파일 입출력을 통하여 엑셀 파일을 가져옵니다.
poi 의존성을 이용하여 엑셀에 담겨진 주차장 데이터를 추출합니다.
추출한 주차장 데이터를 최신순으로 정렬하여 클라이언트에 반환합니다.

## ✅ Tasks
- [x] poi 의존성 추가
- [x] 파일 입출력을 통해 엑셀 파일 추가
- [x] poi 의존성을 이용하여 파일로부터 주차장 데이터 추출
- [x] 추출한 주차장 데이터 최신순 정렬
- [x] 주차장 데이터 반환 API 구현

## 🙋🏻 More
사용하는 엑셀 내 데이터는 더미 데이터이기 때문에, 추후 로직이 변경될 예정입니다.
